---
- name: Check if texinfo is already installed and get version
  changed_when: false
  shell: makeinfo --version | sed -n '1p' | awk '{print $4}'
  ignore_errors: true
  register: makeinfo_output

- include_tasks: install_texinfo.yml
  when:
    - makeinfo_output is defined
    - makeinfo_output.stdout is defined
    - makeinfo_output.stdout != texinfo_version|string
